#!/usr/bin/env bash
# =============================================================================
# provision-authelia.sh — generate the Authelia user database from .env and
# (re)start the `authelia` container.
#
#   sudo bash scripts/provision-authelia.sh [--dry-run] [--no-hash]
#
# Authelia is the forward-auth / SSO gate in front of protected vhosts
# (chat.hellyer.kiwi today). It is its own container, config in ./authelia,
# data (SQLite DB + user database + notifier) under ~/www/auth.hellyer.kiwi.
#
# The initial user is created from AUTHELIA_ADMIN_USER / AUTHELIA_ADMIN_EMAIL /
# AUTHELIA_ADMIN_PASSWORD in .env. The password is hashed with the Authelia
# binary itself (`authelia hash-password`); the plaintext never lands on disk
# beyond .env, and the generated users_database.yml is gitignored and
# snapshot-backed.
#
# This script is the STANDALONE entry point: it creates its own data dir and
# starts the container, so it does not require a (destructive) full deploy.sh.
# It does need .env (with the AUTHELIA_* secrets + admin password) and a
# running podman/compose stack. Run from anywhere; re-running is safe.
#
# Idempotent: re-running regenerates users_database.yml from the current .env
# values and restarts the container. Pass --no-hash to skip re-hashing (only
# rewrites file/metadata) — not usually needed.
#
# Options: --dry-run, --no-hash
#
# Config: AUTHELIA_* in .env (see .env.example / compose.yaml).
# =============================================================================
set -euo pipefail
cd "$(dirname "$0")/.."
[ -f .env ] && set -a && source .env && set +a
source scripts/lib-containers.sh
source scripts/lib-paths.sh
source scripts/lib-env.sh

WWW_ROOT="$(resolve_www_root)"
DATA_DIR="$WWW_ROOT/auth.hellyer.kiwi"
ADMIN_USER_RESOLVED="$(resolve_admin_user)"

say()  { printf '\033[1;36m==>\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[ok]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[!!]\033[0m %s\n' "$*"; }
die()  { printf '\033[1;31m[xx]\033[0m %s\n' "$*" >&2; exit 1; }

DRY=0; DO_HASH=1
while [ $# -gt 0 ]; do
  case "$1" in
    --dry-run) DRY=1; shift ;;
    --no-hash) DO_HASH=0; shift ;;
    -h|--help) sed -n '2,26p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "Unknown option: $1" ;;
  esac
done
run() { if [ "$DRY" = 1 ]; then printf '    DRY: %s\n' "$*"; else "$@"; fi; }

USERS_FILE="$DATA_DIR/users_database.yml"

# ---- validate required settings --------------------------------------------
AUTHELIA_ADMIN_USER="${AUTHELIA_ADMIN_USER:-}"
AUTHELIA_ADMIN_EMAIL="${AUTHELIA_ADMIN_EMAIL:-}"
AUTHELIA_ADMIN_PASSWORD="${AUTHELIA_ADMIN_PASSWORD:-}"
AUTHELIA_IMAGE="docker.io/authelia/authelia:4.39"

[ -n "$AUTHELIA_ADMIN_USER" ]     || die "AUTHELIA_ADMIN_USER is not set in .env."
[ -n "$AUTHELIA_ADMIN_EMAIL" ]    || die "AUTHELIA_ADMIN_EMAIL is not set in .env."
[ -n "$AUTHELIA_ADMIN_PASSWORD" ] || die "AUTHELIA_ADMIN_PASSWORD is not set in .env."

[ -n "${AUTHELIA_SESSION_SECRET:-}" ] && [ -n "${AUTHELIA_STORAGE_ENCRYPTION_KEY:-}" ] \
  || die "AUTHELIA_SESSION_SECRET / AUTHELIA_STORAGE_ENCRYPTION_KEY missing — run scripts/deploy.sh first (it generates them)."

# ---- 1. data dir + hash the password ---------------------------------------
say "Ensuring data dir $DATA_DIR"
run mkdir -p "$DATA_DIR"

HASH="$AUTHELIA_ADMIN_PASSWORD"
if [ "$DO_HASH" = 1 ]; then
  say "Hashing the admin password with the Authelia binary"
  if [ "$DRY" = 1 ]; then
    echo "    DRY: podman run --rm $AUTHELIA_IMAGE authelia hash-password <redacted>"
    HASH='$argon2id$REDACTED'
  else
    HASH="$(printf '%s' "$AUTHELIA_ADMIN_PASSWORD" \
      | podman run --rm -i "$AUTHELIA_IMAGE" authelia hash-password 2>/dev/null \
      | awk 'NR==1{print $NF}')"
    case "$HASH" in
      \$argon2*) : ;;
      *) die "Could not hash the password (got '$HASH'). Is the image pullable? Try: podman pull $AUTHELIA_IMAGE" ;;
    esac
  fi
fi

# ---- 2. write users_database.yml -------------------------------------------
# Quote the hash: it contains $ and would otherwise be mangled by YAML/shell.
say "Writing $USERS_FILE"
if [ "$DRY" = 1 ]; then
  echo "    DRY: write users_database.yml for '$AUTHELIA_ADMIN_USER' <$AUTHELIA_ADMIN_EMAIL>"
else
  cat > "$USERS_FILE" <<EOF
# Generated by scripts/provision-authelia.sh — DO NOT EDIT BY HAND.
# Rewritten from AUTHELIA_ADMIN_* in .env every time provisioning runs.
# This file lives under ~/www so it is included in the nightly snapshot.
users:
  ${AUTHELIA_ADMIN_USER}:
    displayname: '${AUTHELIA_ADMIN_USER}'
    password: '${HASH}'
    email: '${AUTHELIA_ADMIN_EMAIL}'
    groups:
      - 'admins'
EOF
  chmod 600 "$USERS_FILE"
  # Container runs as root (user: "0:0"); keep the dir usable by the admin user too.
  chown -R "$ADMIN_USER_RESOLVED:$ADMIN_USER_RESOLVED" "$DATA_DIR" 2>/dev/null || true
  ok "Wrote user database for '$AUTHELIA_ADMIN_USER'."
fi

# ---- 3. bring up the container ---------------------------------------------
say "Bringing up the authelia service"
if [ "$DRY" = 1 ]; then
  echo "    DRY: podman compose up -d authelia"
else
  if podman compose version >/dev/null 2>&1; then podman compose up -d authelia; else podman-compose up -d authelia; fi
fi

# ---- 4. wait for health -----------------------------------------------------
if [ "$DRY" != 1 ]; then
  say "Waiting for Authelia on http://127.0.0.1:9091/api/health (via the container network)"
  up=0
  for _ in $(seq 1 30); do
    if podman exec "$CONTAINER_AUTHELIA" wget -qO- http://127.0.0.1:9091/api/health >/tmp/authelia-health.json 2>/dev/null; then
      ok "Authelia is up: $(cat /tmp/authelia-health.json)"; up=1; break
    fi
    sleep 3
  done
  [ "$up" = 1 ] || warn "Authelia did not answer in 90s — check: podman logs authelia"
fi

# ---- 5. reload nginx --------------------------------------------------------
if [ "$DRY" != 1 ]; then
  podman exec "$CONTAINER_NGINX" nginx -t >/dev/null 2>&1 \
    && podman exec "$CONTAINER_NGINX" nginx -s reload >/dev/null 2>&1 || true
fi
ok "Done: authelia"
